undefined-academy/semana-2

student-cvs/aitorias-9443/contact.html, student-cvs/aitorias-9443/index.html, student-cvs/aitorias-9443/main.js, student-cvs/aitorias-9443/styles.css
Para este proyecto he actualizado mi hoja de vida con elementos de HTML semánticos y reestructurado el contenido para cumplir con los requisitos del [Markup Validation Service W3C&reg; ](https://validator.w3.org/nu/).
Los pasos que he seguido para realizar dicho _pull request_ son:
1. Realizar el _fork_ del repositorio de la semana 2 de [Undefined Academy](https://github.com/undefined-academy/semana-2).
2. Hacer un `git clone` de dicho repositorio.
3. Hacer una copia de los archivos `index.html` y `styles.css` de mi hoja de vida del repositorio de la semana 1, y una un `commit` y `push` de ambos archivos a mi repositorio clonado.
4. Finalmente, creo este _pull request_ en el repositorio original de Undefined Academy.
=> Aitorias-9443 pull request

student-cvs/Peke-4001/index.html, student-cvs/Peke-4001/styles.css
- fork al repositorio de la semana-2
- crear carpeta dentro de student-cvs que lleve de nombre el usuario de discord
- copiar archivos .html y .css de la semana-1
- aplicar html semantico al archivo .html
=> Ejercicio semana 2 - aplicando html semantico

.vscode/settings.json, student-cvs/gustavo.arana-6562/index.html, student-cvs/gustavo.arana-6562/style.css
1. Prepare your GitHub account:
* Create or sign up for an account on [GitHub](https://github.com/)
> If this link doesn´t work, copy and paste this URL into your browser ****https://github.com/****
* Open this [link](https://gitgub.com/undefined-academy/semana-2) containing the repository to fork: Repository **semana-2**
> If this link doesn´t work, copy and paste this URL into your browser ****https://gitgub.com/undefined-academy/semana-2****
2. On the **semana-2** repository, click on the **Fork** button and select **Create a new fork**
> This action creates a copy of the **semana-2** repository in your GitHub account.
3. Open your terminal and execute the command `git clone [URL_OF_YOUR_FORKED_REPOSITORY]`
* Open your forked repository on a browser
* Click the **Code** button
* Click …
=> Pull request gustavo.arana6562

student-cvs/giot99-7609/contacto.html, student-cvs/giot99-7609/index.html, student-cvs/giot99-7609/styles.css
=> semana 2-clase 1-html semantico

student-cvs/crbm456-0270/contacto.html, student-cvs/crbm456-0270/index.html, student-cvs/crbm456-0270/styles.css
>1.HTML semántico
2.Formularios
=> PR semana 2 

student-cvs/haboufaker-8509/README.md, student-cvs/haboufaker-8509/index.html, student-cvs/haboufaker-8509/styles.css
=> HTML Semantico

student-cvs/luanarmo-7586/index.html, student-cvs/luanarmo-7586/main.js, student-cvs/luanarmo-7586/style.css
- Agregando HTML semantico a mi cv ✅
- Agregando formulario de contacto a mi cv ✅
=> luanarmo-7586 Agregando ejercicios semana 2

student-cvs/gab-3881/index.html, student-cvs/gab-3881/styles.css
Para los ejercicios correspondientes a la semana-2: 
1. Realicé un fork del repositiorio
2. Cloné el repositorio al cual le hice fork
3. Validé mi HTML
4. Tomé como punto de partida el HTML y CSS creados en la semana anterior
5. Hice desde cero el HTML y CSS de mi nuevo perfil, añadí nuevas cosas y lo modifiqué para que tuviera sentido semántico.
6. Añadí un formulario de contacto al final de mi documento HTML
=> gab-3881 - Semana 2 - PR

.gitignore, student-cvs/manuel77-7331/index.html, student-cvs/manuel77-7331/styles.css
1. Apply semantic HTML
2. Add form contact
=> Pull Request Week 2

README.md, student-cvs/equiman-0343/README.md, student-cvs/equiman-0343/contact.html, student-cvs/equiman-0343/exercise/class-1.js, student-cvs/equiman-0343/exercise/class-2.js, student-cvs/equiman-0343/index.html, student-cvs/equiman-0343/main.css, student-cvs/equiman-0343/main.js, student-cvs/equiman-0343/warnup/class-1.js, student-cvs/equiman-0343/warnup/class-2.js
Gracias por sacar de tu tiempo para revisa mi PR. Te dejo como agradecimiento una bonita obra de música clásica que puedes escuchar de fondo mientras realizas la revision: [Bolero - Maurice Ravel](https://www.youtube.com/watch?v=V3WH4gF84fU).
- Se crea hace un fork del repositorio principal
- Luego se clona al equipo el nuevo fork
- Realice los ejercicios y las pruebas de calentamiento
- Copie los archivos aprobados de la semana 1
- Actualize el HTML usando etiquetas semánticas
- Realize la validación y correcciones recomendadas por la herramienta de la W3C
- Actualize los colores usando como base la gama sky de Tailwind CSS (usando variables de CSS)
- Cree una nueva página para el formulario de contáctenos
- Enlace el formulario desde la página principal y agregue un botón para regresar …
=> Etiquetas semánticas y formulario de contacto

student-cvs/Carolina08001-6984/contact.html, student-cvs/Carolina08001-6984/index.html, student-cvs/Carolina08001-6984/styles.css
##HTML Semántico
1. He creado un archivo html con el formato de una hoja de vida.
2. Le di estilos con CSS para que tuviera color y se vea bien el pantalla de pc, aun no está responsive.
3. Pase mi codigo html por el [validador](https://validator.w3.org/), y no me lanzó errores.
4. Agregé los archivos con git add a la lista de archivos trackeados, luego git commit, y al final git push origin main.
=> html semantico- version 01

student-cvs/Seujumon-1612/CSS/eform.css, student-cvs/Seujumon-1612/CSS/estilos.css, student-cvs/Seujumon-1612/README.md, student-cvs/Seujumon-1612/form.html, student-cvs/Seujumon-1612/index.html
Comienzo a subir los ejercicios de la semana 2 del Bootcamp.
=> Añado archivos de la semana 2

student-cvs/Angel-Mijares-3276/contacto.css, student-cvs/Angel-Mijares-3276/contacto.html, student-cvs/Angel-Mijares-3276/index.html, student-cvs/Angel-Mijares-3276/style.css
Cambios de la hoja de vida de la semana 1, con HTML semántico.
=> Update HTML Semántico

student-cvs/FTACapa-8510/index.html, student-cvs/FTACapa-8510/main.js, student-cvs/FTACapa-8510/styles.css
1 - Realize un fork del repositorio de la semana 2.
2 - Agregue mi archivo index.html de la semana 1.
3 - Agregue mi archivo styles.css de la semana 1.
4- Actualize mi archivo index.html y agregue etiquetas de HTML semantico.
=> Semantic HTML Class 3 Week 2

student-cvs/bautista-lonardi-9435/index.html, student-cvs/bautista-lonardi-9435/script.js, student-cvs/bautista-lonardi-9435/style.css
Rediseñé la web, agregue unas secciones nuevas y maqueté con html semántico.
=> Mi web personal, maquetada con html semantico

.gitignore, student-cvs/taliixer-8876/index.html, student-cvs/taliixer-8876/style.css
1. Creation of the curriculum vitae
2. Use HTML semantics in index.html
3. Add styles to the CV with a good layout
4. Use flexbox and css grid
5. Create a responsive page
=> Finishes week 2

student-cvs/schnoodle-3247/index.html, student-cvs/schnoodle-3247/style.css
Ejercicio de HTML semántico Semana 2 clase 3
=> HTML semántico

student-cvs/sebasrico-3054/contactenos.html, student-cvs/sebasrico-3054/css/style-contactenos.css, student-cvs/sebasrico-3054/css/style.css, student-cvs/sebasrico-3054/index.html, student-cvs/sebasrico-3054/paginaDestino.html
Ejercicio 2 , semana 2.
Seguimos avanzando con toda.
=> Ejercicio-semana2

.gitignore, .vscode/settings.json, student-cvs/augaldecr-4610/index.html, student-cvs/augaldecr-4610/styles.css
Creación de nueva estructura de cv. Adición de etiquetas semánticas, corrección del outline y corrección de estilos
=> Clase 3 y clase 4

student-cvs/r4vc31-7548/index.html, student-cvs/r4vc31-7548/style.css
1. Starting with the basic info for the CV page (HTML & CSS)
2. Adding a Contact Section.
=> Exercises (Week 2)

student-cvs/GariCarandai-2859/index.html, student-cvs/GariCarandai-2859/style.css
**Pasos que he realizados para completar la práctica:**
1. Le he dado al botón Fork del repositorio [/undefined-academy/semana-2](https://github.com/undefined-academy/semana-2) para hacer una copia en mi perfil de github.
2. Con el comando `git clone` he clonado el repositorio en mi latpop.
3. Haciendo usos de mis nuevos e increíbles conocimientos de los comando de la terminal, he copiado la estructura de archivos del repositorio local: semana-1 y los he pegado en el nuevo.
4. He analizado la estructura jerárquica de mi código html en la web: [https://validator.w3.org/nu/](https://validator.w3.org/nu/) y he restructurado el contenido añadiendo las etiquetas aprendidas en clase.
5. Por último he commiteado/pusheado fuertemente mi nuevo content (previamente añadido al staging) y le he dado …
=> GariCarandai-2859

student-cvs/tigret0n-6769/index.html, student-cvs/tigret0n-6769/main.js, student-cvs/tigret0n-6769/styles.css
Hoja de vida con formulario incluido y archivo JS para prevenir evento por defecto del botón tipo submit.
=> tigret0n-6769 cv y form

student-cvs/manuelpryda-7878/contact.html, student-cvs/manuelpryda-7878/index.html, student-cvs/manuelpryda-7878/style.css
Fork del repositorio semana-2
git clone git@github.com:/semana-2.git -> 
git add .
git push origin main
En nuestro repositorio forkeado de Github hacer el pull request
=> cambios html y css

student-cvs/JoseHerrera-9309/contacto.html, student-cvs/JoseHerrera-9309/index.html, student-cvs/JoseHerrera-9309/main.css
Agrego etiquetas de HTML semanticas
=> Agrego html semantico

student-cvs/emporto95-7729/contact.html, student-cvs/emporto95-7729/index.html, student-cvs/emporto95-7729/style.css
* He tomado mi archivo index.html que contenia mi curriculum y lo he transformado para agregarle HTML semantico.
* Copie el codigo de mi archivo y lo pegue en el validador semantico de HTML para asegurarme de que estaba todo correctamente estructurado.
* Luego le agregue algunos arreglos esteticos y cree el Pull Request
=> Curriculum actualizado con HTML semantico

student-cvs/Diego-3282/index.html, student-cvs/Diego-3282/styles.css
- Ajustando el html con etiquetas semanticas
=> Diego-3282 pull request Semana-2 

student-cvs/monh-6851/formulario_contacto.css, student-cvs/monh-6851/formulario_contacto.html, student-cvs/monh-6851/index.html, student-cvs/monh-6851/main.css
Enunciado tarea: Cambiar las etiquetas de tu hoja de vida para hacer uso de etiquetas semánticas
- index.html
- main.css
Enunciado tarea:  En el mismo Pull Request de la semana-2, agregar para tu hoja de vida una sección o página nueva de contacto que haga uso de los formularios de HTML
- formulario_contacto.html
- formulario_contacto.css
=> Tarea Semana 2, HTML Semántico
